# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: safeSocket.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'safeSocket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10safeSocket.proto\x12\x07Helpers\"h\n\x08HelloMsg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08selfHost\x18\x02 \x01(\t\x12\x10\n\x08selfPort\x18\x03 \x01(\t\x12\x14\n\x0cselfSockName\x18\x04 \x01(\t\x12\x14\n\x0cselfPublicIp\x18\x05 \x01(\tB\x03Z\x01/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'safeSocket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001/'
  _globals['_HELLOMSG']._serialized_start=29
  _globals['_HELLOMSG']._serialized_end=133
# @@protoc_insertion_point(module_scope)
