// source: Qmsg.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Qmsg.StreamMsg');
goog.provide('proto.Qmsg.StreamMsg.StreamAction');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Qmsg.StreamMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Qmsg.StreamMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Qmsg.StreamMsg.displayName = 'proto.Qmsg.StreamMsg';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Qmsg.StreamMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.Qmsg.StreamMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Qmsg.StreamMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Qmsg.StreamMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
broker: jspb.Message.getFieldWithDefault(msg, 1, ""),
streamAction: jspb.Message.getFieldWithDefault(msg, 2, 0),
ticker: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Qmsg.StreamMsg}
 */
proto.Qmsg.StreamMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Qmsg.StreamMsg;
  return proto.Qmsg.StreamMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Qmsg.StreamMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Qmsg.StreamMsg}
 */
proto.Qmsg.StreamMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBroker(value);
      break;
    case 2:
      var value = /** @type {!proto.Qmsg.StreamMsg.StreamAction} */ (reader.readEnum());
      msg.setStreamAction(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Qmsg.StreamMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Qmsg.StreamMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Qmsg.StreamMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Qmsg.StreamMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBroker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStreamAction();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.Qmsg.StreamMsg.StreamAction = {
  QUOTE: 0,
  UNQUOTE: 1,
  TICK: 2,
  UNTICK: 3,
  ORDERBOOK: 4,
  UNORDERBOOK: 5
};

/**
 * optional string BROKER = 1;
 * @return {string}
 */
proto.Qmsg.StreamMsg.prototype.getBroker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Qmsg.StreamMsg} returns this
 */
proto.Qmsg.StreamMsg.prototype.setBroker = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional StreamAction STREAM_ACTION = 2;
 * @return {!proto.Qmsg.StreamMsg.StreamAction}
 */
proto.Qmsg.StreamMsg.prototype.getStreamAction = function() {
  return /** @type {!proto.Qmsg.StreamMsg.StreamAction} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.Qmsg.StreamMsg.StreamAction} value
 * @return {!proto.Qmsg.StreamMsg} returns this
 */
proto.Qmsg.StreamMsg.prototype.setStreamAction = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string TICKER = 3;
 * @return {string}
 */
proto.Qmsg.StreamMsg.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Qmsg.StreamMsg} returns this
 */
proto.Qmsg.StreamMsg.prototype.setTicker = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


