# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backendDb.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'backendDb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62\x61\x63kendDb.proto\x12\nMyDatabase\"\x89\x04\n\x08LogDbMsg\x12\x11\n\tTimestamp\x18\x01 \x01(\t\x12\x10\n\x08Hostname\x18\x02 \x01(\t\x12\x12\n\nLoggerName\x18\x03 \x01(\t\x12\x0e\n\x06Module\x18\x04 \x01(\t\x12/\n\x05Level\x18\x05 \x01(\x0e\x32 .MyDatabase.LogDbMsg.LevelNumber\x12\x10\n\x08\x46ilename\x18\x06 \x01(\t\x12\x14\n\x0c\x46unctionName\x18\x07 \x01(\t\x12\x12\n\nLineNumber\x18\x08 \x01(\t\x12\x0f\n\x07Message\x18\t \x01(\t\x12\x10\n\x08PathName\x18\n \x01(\t\x12\x11\n\tProcessId\x18\x0b \x01(\t\x12\x13\n\x0bProcessName\x18\x0c \x01(\t\x12\x10\n\x08ThreadId\x18\r \x01(\t\x12\x12\n\nThreadName\x18\x0e \x01(\t\x12\x13\n\x0bServiceName\x18\x0f \x01(\t\x12\x12\n\nStackTrace\x18\x10 \x01(\t\"\xac\x01\n\x0bLevelNumber\x12\x0e\n\nunloggable\x10\x00\x12\n\n\x06notset\x10\x01\x12\t\n\x05\x64\x65\x62ug\x10\x02\x12\n\n\x06stream\x10\x03\x12\x08\n\x04info\x10\x04\x12\t\n\x05logon\x10\x05\x12\n\n\x06logout\x10\x06\x12\t\n\x05trade\x10\x07\x12\x0c\n\x08schedule\x10\x08\x12\n\n\x06report\x10\t\x12\x0b\n\x07warning\x10\n\x12\t\n\x05\x65rror\x10\x0b\x12\x0c\n\x08\x63ritical\x10\x0c\x42\x03Z\x01/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backendDb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001/'
  _globals['_LOGDBMSG']._serialized_start=32
  _globals['_LOGDBMSG']._serialized_end=553
  _globals['_LOGDBMSG_LEVELNUMBER']._serialized_start=381
  _globals['_LOGDBMSG_LEVELNUMBER']._serialized_end=553
# @@protoc_insertion_point(module_scope)
